name: CI-CD

# Controls when the action will run.
on:
  push

jobs:
  build-test:
    runs-on: ubuntu-22.04
    container:
      image: yanzhaowang/r3bdev:fedora-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: testing
        run: |
          ${SIMPATH}/bin/root-config --cxxstandard
          ${SIMPATH}/bin/root-config --cxx
          ${SIMPATH}/bin/root -q test.C
          printenv

      - name: testing failing
        run: |
          ${SIMPATH}/bin/root -q test_fail.C
