name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow in case of a push or pull request events
  push:
    branches: [dev, edwin_dev]
  pull_request:
    branches: [dev, edwin_dev]

